import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import Navigation from './components/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Testvalley App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-default-50'>
          <Navigation />
        </div>
        <div className='bg-default-50 lg:bg-white'>{children}</div>
      </body>
    </html>
  );
}
